import QuestionBank from './repo'
import Response from '../../utils/Responses';

exports.create = async (req, res) => {
    try {
        const {
            firstName,
            lastName,
            school,
            questionBankClass
        } = req.body;

        QuestionBank.create(firstName, lastName, school, questionBankClass)
        .then(results => {
            Response.Success(res, 200, "created successfully", results);
        })
        .catch(err => {
            console.log(err);
            Response.InternalServerError(res, "We are having issues! please try again soon");
        });

    } catch (error) {
        console.log(error);
        Response.InternalServerError(res, "We are having issues! please try again soon");
    }
    
}

exports.update = async (req, res) => {
    try {
        const questionBankId = req.params.questionBankId;
        const {
            firstName,
            lastName,
            questionBankClass
        } = req.body;
        QuestionBank.update(questionBankId, firstName, lastName, questionBankClass)
            .then(results => {
                Response.Success(res, 200, "updated successfully", results);
            })
            .catch(err => {
                console.log(err);
                Response.InternalServerError(res, "We are having issues! please try again soon");
            });

    } catch (error) {
        console.log(error);
        Response.InternalServerError(res, "We are having issues! please try again soon");
    }
    
}

exports.getAllClassQuestionBanks = async (req, res) => {
    try {
        const classId = req.params.classId;
        QuestionBank.getAllClassQuestionBanks(classId)
            .then(results => {
                Response.Success(res, 200, "queried successfully", results);
            })
            .catch(err => {
                console.log(err);
                Response.InternalServerError(res, "We are having issues! please try again soon");
            });

    } catch (error) {
        console.log(error);
        Response.InternalServerError(res, "We are having issues! please try again soon");
    }
    
}

exports.getAllSchoolQuestionBanks = async (req, res) => {
    try {
        const schoolId = req.params.schoolId;
        QuestionBank.getAllSchoolQuestionBanks(schoolId)
            .then(results => {
                Response.Success(res, 200, "queried successfully", results);
            })
            .catch(err => {
                console.log(err);
                Response.InternalServerError(res, "We are having issues! please try again soon");
            });

    } catch (error) {
        console.log(error);
        Response.InternalServerError(res, "We are having issues! please try again soon");
    }
    
}

exports.getOneQuestionBank = async (req, res) => {
    try {
        const questionBankId = req.params.questionBankId;

        QuestionBank.getOneQuestionBank(questionBankId)
            .then(results => {
                Response.Success(res, 200, "queried successfully", results);
            })
            .catch(err => {
                console.log(err);
                Response.InternalServerError(res, "We are having issues! please try again soon");
            });

    } catch (error) {
        console.log(error);
        Response.InternalServerError(res, "We are having issues! please try again soon");
    }
    
}

exports.delete = async (req, res) => {
    try {
        const questionBankId = req.params.questionBankId;
        
        QuestionBank.delete(questionBankId)
            .then(results => {
                Response.Success(res, 200, "deleted successfully", results);
            })
            .catch(err => {
                console.log(err);
                Response.InternalServerError(res, "We are having issues! please try again soon");
            });

    } catch (error) {
        console.log(error);
        Response.InternalServerError(res, "We are having issues! please try again soon");
    }
    
}